#include "emitters/c_header.hpp"
#include <sstream>
namespace bridgeabi::generator {
namespace {
std::string c_type(const std::string& type) { if (type == "void") return "void"; if (type == "i32") return "int32_t"; if (type == "u32") return "uint32_t"; if (type == "u64") return "uint64_t"; if (type == "f32") return "float"; if (type == "f64") return "double"; if (type == "string") return "bridge::string_view"; if (type == "buffer") return "bridge::buffer_view"; return "void* /* unsupported type: " + type + " */"; }
std::string result_type(const std::string& type) { return (type == "string" || type == "buffer") ? "bridge::owned_buffer" : c_type(type); }
}
std::string emit_c_header(const interface_definition& definition) {
  std::ostringstream output; const auto table = definition.name + "_v" + std::to_string(definition.major);
  output << "// Generated by bridgeabi. Do not edit.\n#pragma once\n#include <bridgeabi/plugin.hpp>\n\nnamespace bridge_generated {\n";
  output << "inline constexpr const char " << definition.name << "_id[] = \"" << definition.id << "\";\n";
  output << "struct " << table << " {\n  std::uint32_t struct_size{sizeof(" << table << ")};\n  std::uint32_t abi_major{" << definition.major << "};\n  std::uint32_t abi_minor{" << definition.minor << "};\n  void* instance{};\n";
  for (const auto& method : definition.methods) { output << "  bridge::status (BRIDGEABI_CALL *" << method.name << ")(void*"; for (const auto& arg : method.parameters) output << ", " << c_type(arg.type) << " " << arg.name; if (method.result_type != "void") output << ", " << result_type(method.result_type) << "* result"; output << ") noexcept {};\n"; }
  output << "  void (BRIDGEABI_CALL *retain)(void*) noexcept {};\n  void (BRIDGEABI_CALL *release)(void*) noexcept {};\n};\n} // namespace bridge_generated\n"; return output.str();
}
} // namespace bridgeabi::generator
